import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Head from "next/head";
import Container from "@/components/Container";

import { Oswald } from "next/font/google";

const oswald = Oswald({preload: false});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={oswald.className + " bg-bgscreen min-h-screen w-full"}>
        <Navbar />
        <Container type="primary">
          <main className="flex w-full justify-start">
            {children}
          </main>
        </Container>
      </body>
    </html>
  );
}
